accounts/urls.py
from django.urls import path
from accounts import views
from accounts import views as accounts_view


app_name = 'accounts'

urlpatterns = [

    # path('login', accounts_view.user_login, name='login'),
    path('Contas/Login', accounts_view.user_authentication, name='login'),
    path('Contas/Logout', accounts_view.user_logout, name='logout'),   
    path('Contas/Lock-screen', views.lock_screen, name='lock-screen'),

    path('Contas/Novo-Usuario/<int:notification_pk>/User-ID/<int:id>/', views.UserNotification.as_view(), name='user-notification'),


]

administration/urls.py
from django.urls import path
from administration import views

app_name = 'administration'

urlpatterns = [
    path('Administracao/Pendencias/', views.admin_list_request, name='admin_list_request'),
    path('Administracao/Em-Analise/', views.admin_list_analyse_request, name='admin_list_analyse_request'),
    path('Administracao/Finalizados/', views.admin_list_finished_request, name='admin_list_finished_request'),
    path('Administracao/Pendencias/Responder/Chamado-N-<int:id>', views.admin_update_request, name='admin_update_request'),
    path('Administracao/Chamados-Antigos/', views.admin_list_chamados_antigos, name='admin_list_chamados_antigos'),
    path('Administracao/Chamados-Antigos/Detalhes/Chamado-N-<int:id>', views.admin_details_chamados_antigos, name='admin_details_chamados_antigos'),  
    path('Administracao/Auditoria/Logins/', views.admin_list_login_audit, name='admin_list_login_audit'),
    path('Administracao/Pesquisar/Resultados/', views.navbar_search, name='navbar_search'),
]

configurations/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    re_path(r'^$', RedirectView.as_view(url='/Chamado/')),
    path('Chamado/', include('accounts.urls')), 
    path('Chamado/', include('solicitation.urls')), 
    path('Chamado/', include('administration.urls')), 
    path('Chamado/', include('help_pages.urls')), 
    path('Chamado/', include('notifications.urls')), 
    path('Administracao-Chamado-DP-TI/', admin.site.urls),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/urls.py
from django.urls import path
from notifications import views  


app_name = 'notifications'

urlpatterns = [
    path('Notificacoes/<int:notification_pk>/Solicitacao/<int:id>', views.PostNotification.as_view(), name='post-notification'),
    path('Notificacoes/Minhas-Notificacoes/', views.list_notifications, name='list_notifications'),
    path('Notificacoes/Minhas-Notificacoes/Partials', views.partial_notifications, name='partial_notifications'),
    
    path('Notificacoes/Minhas-Notificacoes/Arquivadas/', views.list_notifications_archive, name='list_notifications_archive'),
    path('Notificacoes/Minhas-Notificacoes/Partials/Arquivadas', views.partial_notifications_archive, name='partial_notifications_archive'),

    path('Notificacoes/Minhas-Notificacoes/Marcar-Como-Lida/<int:notification_pk>/', views.mark_as_read, name='mark_as_read'),
    path('Notificacoes/Minhas-Notificacoes/Marcar-Como-Nao-Lida/<int:notification_pk>/', views.mark_as_unread, name='mark_as_unread'),
    path('Notificacoes/Minhas-Notificacoes/Marcar-Todas-Como-Lidas/', views.mark_all_read, name='mark_all_read'),

    path('Notificacoes/Minhas-Notificacoes/Arquivar-Notificacao/<int:notification_pk>/', views.mark_archive, name='mark_archive'),
    path('Notificacoes/Minhas-Notificacoes/Marcar-Todas-Como-Arquivadas/', views.mark_all_archive, name='mark_all_archive'),

    path('Notificacoes/Minhas-Notificacoes/Desarquivar-Notificacao/<int:notification_pk>/', views.mark_unarchive, name='mark_unarchive'),
    path('Notificacoes/Minhas-Notificacoes/Marcar-Todas-Como-Desarquivadas/', views.mark_all_unarchive, name='mark_all_unarchive'),

    path('Notificacoes/Minhas-Notificacoes/Deletar-Notificacao/<int:notification_pk>/', views.delete_notification, name='delete_notification'),
    path('Notificacoes/Minhas-Notificacoes/Deletar-Notificacao/Arquivada/<int:notification_pk>/', views.delete_notification_achive, name='delete_notification_achive'),
    path('Notificacoes/Minhas-Notificacoes/Deletar-Todas-Notificacoes/', views.delete_all_notifications, name='delete_all_notifications'),
    path('Notificacoes/Minhas-Notificacoes/Deletar-Todas-Notificacoes/Arquivadas/', views.delete_all_archive, name='delete_all_archive'),
]

solicitation/urls.py
from django.urls import path
from solicitation import views

app_name = 'solicitation'

urlpatterns = [
    path('', views.index, name='index'),
    path('Solicitar/', views.make_request, name='make_request'),
    path('Meus-Chamados/', views.user_list_request, name='user_list_request'),
    path('Meus-Chamados/Detalhes/Chamado-N-<int:id>', views.details_request, name='datails_requests'),  
    path('Meus-Chamados/Editar/Chamado-N-<int:id>', views.update_request, name='update_request'), 
]

templates/partials/_footer.html
{% load static %} 
<footer class="footer">
    <div class="row g-0 justify-content-between fs--1 mt-4 mb-3">
        <div class="col-12 col-sm-auto text-center">
            <p class="mb-0 text-600">
                <a href="#Desenvolvedor=CB_PM_162131-9_Bruno_Alves_#Email=bruno6821@gmail.com">Made with Python and Django</a>
                <span class="d-none d-sm-inline-block">| </span>
                <br class="d-sm-none" /> 2023 &copy; 
                <a href="http://www.intranet2.dp.policiamilitar.sp.gov.br/" target="_blank">Diretoria de Pessoal</a>  
                <a class="text-danger fw-bold" href="" 
                target="_blank"></a>
            </p>
        </div>
        <div class="col-12 col-sm-auto text-center">
            <p class="mb-0 text-600">v.0.2.2</p>
        </div>
    </div>
</footer>

templates/partials/_header.html
   {% load static %} 
 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="title" content="Sistema de Chamados da Diretoria de Pessoal">
    <meta name="description" content="Sistema desenvolvido para Suporte aos Usuários">
    <meta name="keywords" content="Chamado-DP, Help-Desk">
    <meta name="robots" content="noindex, nofollow">
    <meta name="language" content="Portuguese">   
    <meta name="developer" content="Cabo PM Bruno Alves - 162131-9">   
    

    <meta name="theme-color" content="#ffffff">
    <script src="{% static 'js/config.js' %}"></script>
    <script src="{% static 'vendors/overlayscrollbars/OverlayScrollbars.min.js' %}"></script>
   <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link rel="preconnect" href="https://fonts.gstatic.com/">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700%7cPoppins:300,400,500,600,700,800,900&amp;display=swap" rel="stylesheet">
    <link href="{% static 'vendors/overlayscrollbars/OverlayScrollbars.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/theme-rtl.min.css' %}" rel="stylesheet" id="style-rtl" disabled>
    <link href="{% static 'css/theme.min.css' %}" rel="stylesheet" id="style-default">
    <link href="{% static 'css/personalizados.css' %}" rel="stylesheet">
    <link href="{% static 'css/user-rtl.min.css' %}" rel="stylesheet" id="user-style-rtl" disabled>
    <link href="{% static 'css/user.min.css' %}" rel="stylesheet" id="user-style-default">

    <script>
      var isRTL = JSON.parse(localStorage.getItem('isRTL'));
      if (isRTL) {
        var linkDefault = document.getElementById('style-default');
        var userLinkDefault = document.getElementById('user-style-default');
        linkDefault.setAttribute('disabled', true);
        userLinkDefault.setAttribute('disabled', true);
        document.querySelector('html').setAttribute('dir', 'rtl');
      } else {
        var linkRTL = document.getElementById('style-rtl');
        var userLinkRTL = document.getElementById('user-style-rtl');
        linkRTL.setAttribute('disabled', true);
        userLinkRTL.setAttribute('disabled', true);
      }
    </script>

templates/partials/_navtop.html
{% load static %}
{% load _notifications %}  
<nav class="navbar navbar-light navbar-glass navbar-top navbar-expand" style="display: none;">
    <button class="btn navbar-toggler-humburger-icon navbar-toggler me-1 me-sm-3" 
    type="button" data-bs-toggle="collapse" 
    data-bs-target="#navbarVerticalCollapse" 
    aria-controls="navbarVerticalCollapse" 
    aria-expanded="false" aria-label="Toggle Navigation">
        <span class="navbar-toggle-icon">
            <span class="toggle-line">

            </span>
        </span>
    </button>
    <a class="navbar-brand me-1 me-sm-3" href="{% url 'solicitation:index' %} ">
        <div class="d-flex align-items-center">            
            <span class="font-sans-serif">Chamado DP</span>
        </div>
    </a> 

    {% if request.user.is_staff %}
        {% include 'partials/_search_partial.html' %}    
    {% endif %}
         <!-- NOTIFICAÇÕES -->
    <ul class="navbar-nav navbar-nav-icons ms-auto flex-row align-items-center">
        <li>
        <div class="form-check form-switch"><input class="form-check-input ms-0" id="mode-fluid" type="checkbox" data-theme-control="isFluid" /></div>
        </li>
        <li class="nav-item">
            <div class="theme-control-toggle fa-icon-wait px-2">
                <input class="form-check-input ms-0 theme-control-toggle-input" 
                id="themeControlToggle" type="checkbox" data-theme-control="theme" 
                value="dark" />
                <label class="mb-0 theme-control-toggle-label theme-control-toggle-light" 
                for="themeControlToggle" data-bs-toggle="tooltip" data-bs-placement="left" 
                title="Mudar para Modo claro">
                <span class="fas fa-sun fs-0"></span></label><label class="mb-0 theme-control-toggle-label theme-control-toggle-dark" for="themeControlToggle" data-bs-toggle="tooltip" data-bs-placement="left" title="Mudar para modo Escuro"><span class="fas fa-moon fs-0"></span></label></div>
        </li>

        {% system_notification %}

        <li class="nav-item dropdown">
            <a class="nav-link pe-0" id="navbarDropdownUser" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="avatar avatar-xl">
                    <img class="rounded-circle border"
                    src="data:image/png;base64,{{ request.session.fotodecoded }}" />
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-end py-0" aria-labelledby="navbarDropdownUser">
                <div class="bg-white dark__bg-1000 rounded-2 py-2">
                    <a class="dropdown-item fw-bold text-warning text-center"></span><span>Olá </span></a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item fw-bold text-primary text-center"></span><span>{{request.session.nomeguerra|title}} </span></a>
                    {% comment %} <a class="dropdown-item" href="#!">Set status</a> {% endcomment %}
                    {% comment %} <a class="dropdown-item" href=" ">Meu Profile</a>
                    <a class="dropdown-item" href=" ">Feed</a> {% endcomment %}
                    <div class="dropdown-divider"></div>
                    {% comment %} <a class="dropdown-item" href="  ">Configurações</a> {% endcomment %}
                    <a class="dropdown-item" href=" {% url 'accounts:logout' %} ">Logout <i class="fas fa-sign-out-alt"></i></a> 
                </div>
            </div>
        </li>
    </ul>
    <!-- NOTIFICAÇÕES -->
    
</nav>                      
<script>
    var navbarPosition = localStorage.getItem('navbarPosition');
    var navbarVertical = document.querySelector('.navbar-vertical');
    var navbarTopVertical = document.querySelector('.content .navbar-top');
    var navbarTop = document.querySelector('[data-layout] .navbar-top');
    var navbarTopCombo = document.querySelector('.content [data-navbar-top="combo"]');
    if (navbarPosition === 'top') {
        navbarTop.removeAttribute('style');
        navbarTopVertical.remove(navbarTopVertical);
        navbarVertical.remove(navbarVertical);
        navbarTopCombo.remove(navbarTopCombo);
    } else if (navbarPosition === 'combo') {
        navbarVertical.removeAttribute('style');
        navbarTopCombo.removeAttribute('style');
        navbarTop.remove(navbarTop);
        navbarTopVertical.remove(navbarTopVertical);
    } else {
        navbarVertical.removeAttribute('style');
        navbarTopVertical.removeAttribute('style');
        navbarTop.remove(navbarTop);
        navbarTopCombo.remove(navbarTopCombo);
    }
</script>

templates/partials/_search_partial.html
<div class="col-6 mx-2 position-absolute top-50 start-50 translate-middle">
    <form action="{% url 'administration:navbar_search' %}">
        <div class="input-group ">
            <input class="form-control" type="search" 
                placeholder="Digite um RE ou Palava chave"
                name="query"
            />        
            <span class="input-group-text" >
                <span class="font-sans-serif fw-bold" style="color: #4285F4;">Cha</span>
                <span class="font-sans-serif fw-bold" style="color: #EA4335;">ma</span>
                <span class="font-sans-serif fw-bold" style="color: #FBBC05;">do</span>
                <span class="font-sans-serif fw-bold" style="color: #FBBC05;;">o</span>
                <span class="font-sans-serif fw-bold" style="color: #4285F4;">g</span>
                <span class="font-sans-serif fw-bold" style="color: #34A853;">l</span>
                <span class="font-sans-serif fw-bold" style="color: #EA4335;">e</span>
            </span>
        </div>
    </form>
</div> 

templates/partials/_sidemenu.html
{% load static %} 
<nav class="navbar navbar-light navbar-vertical navbar-expand-xl">
    <script>
        var navbarStyle = localStorage.getItem("navbarStyle");
        if (navbarStyle && navbarStyle !== 'transparent') {
            document.querySelector('.navbar-vertical').classList.add(`navbar-${navbarStyle}`);
        }
    </script>
    <div class="d-flex align-items-center">
        <div class="toggle-icon-wrapper">
            <button class="btn navbar-toggler-humburger-icon navbar-vertical-toggle" data-bs-toggle="tooltip" data-bs-placement="left" title="Recolher Menu">
                <span class="navbar-toggle-icon">
                    <span class="toggle-line"></span>
                </span>
            </button>
        </div>
        <a class="navbar-brand" href="{% url 'solicitation:index' %} ">
            <div class="d-flex align-items-center py-3">
                <img class="me-2" src="{% static 'img/logos/DP.png' %}"  width="30">
                <span class="font-sans-serif">DP</span>
            </div>
        </a>
    </div>
    <div class="collapse navbar-collapse" id="navbarVerticalCollapse">
        <div class="navbar-vertical-content scrollbar">
            <ul class="navbar-nav flex-column mb-3" id="navbarVerticalNav">
                <li class="nav-item">
                    <a class="" href="{% url 'solicitation:index' %} ">
                        <div class="d-flex align-items-center">
                            <span class="nav-link-icon">
                                <span class="fas fa-chart-pie"></span>
                            </span>
                            <span class="nav-link-text ps-1">Dashboard</span>
                        </div>
                    </a>
                    <ul class="nav collapse show">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'solicitation:index' %} " aria-expanded="false">
                                <div class="d-flex align-items-center">
                                    <i class="fas fa-home"></i>
                                    <span class="nav-link-text ps-1">Home</span>
                                </div>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'solicitation:make_request' %} " aria-expanded="false">
                                <div class="d-flex align-items-center">
                                    <i class="far fa-plus-square"></i>
                                    <span class="nav-link-text ps-1">Solicitar</span>
                                </div>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'solicitation:user_list_request' %} " aria-expanded="false">
                                <div class="d-flex align-items-center">
                                    <i class="far fa-list-alt"></i>
                                    <span class="nav-link-text ps-1">Meus Chamados</span>
                                </div>
                            </a>
                        </li>                              
                    </ul>
                </li>
                <a class="nav-link" href="#Notificacoes" role="button" data-bs-toggle="collapse" aria-expanded="false" aria-controls="email">
                    <div class="d-flex align-items-center">
                        <span class="nav-link-icon">
                            <span class="fas fa-bell text-primary"></span>
                        </span>
                        <span class="nav-link-text ps-1 text-primary ">Notificações</span>
                    </div>
                </a>
                <ul class="nav collapse show">
                    <li class="nav-item">   
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'notifications:list_notifications' %} " aria-expanded="false">
                                <div class="d-flex align-items-center">
                                    <i class="far fa-envelope"></i>
                                    <span class="nav-link-text ps-1">Caixa de Entrada</span>
                                </div>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'notifications:list_notifications_archive' %} " aria-expanded="false">
                                <div class="d-flex align-items-center">
                                    <i class="fas fa-archive"></i>
                                    <span class="nav-link-text ps-1">Arquivadas</span>
                                </div>
                            </a>
                        </li>  
                    </li>
                </ul>   

                {% if request.user.is_superuser == 1%}
                    <li class="nav-item">
                        <a class="" href="{% url 'solicitation:index' %} ">
                            <div class="d-flex align-items-center">
                                <span class="nav-link-icon">
                                    <span class="fas fa-user-cog"></span>
                                </span>
                                <span class="nav-link-text ps-1">Administração</span>
                            </div>
                        </a>
                        <ul class="nav collapse show">
                            <li class="nav-item">
                                <a class="nav-link" href="/Administracao-Chamado-DP-TI/" aria-expanded="false">
                                    <div class="d-flex align-items-center text-danger">
                                        <i class="fas fa-lock"></i>
                                        <span class="nav-link-text ps-1">Django ADMIN</span>
                                    </div>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'administration:admin_list_request' %} " aria-expanded="false">
                                    <div class="d-flex align-items-center">
                                        <i class="far fa-hourglass"></i>
                                        <span class="nav-link-text ps-1">Chamados Pendentes</span>
                                    </div>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'administration:admin_list_analyse_request' %} " aria-expanded="false">
                                    <div class="d-flex align-items-center">
                                        <i class="fas fa-search"></i>
                                        <span class="nav-link-text ps-1">Chamados em Análise</span>
                                    </div>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'administration:admin_list_finished_request' %} " aria-expanded="false">
                                    <div class="d-flex align-items-center">
                                        <i class="far fa-check-square"></i>
                                        <span class="nav-link-text ps-1">Chamados Resolvidos</span>
                                    </div>
                                </a>
                            </li> 
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'administration:admin_list_login_audit' %} " aria-expanded="false">
                                    <div class="d-flex align-items-center">
                                        <i class="far fa-address-card"></i>
                                        <span class="nav-link-text ps-1">Log de Usuários</span>
                                    </div>
                                </a>
                            </li>             
                        </ul>
                    </li>   
                {% endif %}                 
            </ul>
        </div>
    </div>
</nav>
<nav class="navbar-top" style="display: none;"></nav>

templates/partials/js.html
{% load static %} 
<script src="{% static 'vendors/popper/popper.min.js' %}"></script>
<script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'vendors/anchorjs/anchor.min.js' %}"></script>
<script src="{% static 'vendors/fontawesome/all.min.js' %}"></script>
<script src="{% static 'vendors/lodash/lodash.min.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>
<script src="{% static 'vendors/typed.js/typed.js' %}"></script>
<script src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<script src="{% static "vendors/countup/countUp.umd.js" %}"></script>

<script src="{% static "vendors/list.js/list.min.js" %}"></script>

<!-- CSRF request in the headers -->
<script src="https://unpkg.com/htmx.org@1.7.0"></script>