accounts/urls.py
from django.urls import path
from accounts import views
from accounts import views as accounts_view


app_name = 'accounts'

urlpatterns = [

    # path('login', accounts_view.user_login, name='login'),
    path('Contas/Login', accounts_view.user_authentication, name='login'),
    path('Contas/Logout', accounts_view.user_logout, name='logout'),   
    path('Contas/Lock-screen', views.lock_screen, name='lock-screen'),

    path('Contas/Novo-Usuario/<int:notification_pk>/User-ID/<int:id>/', views.UserNotification.as_view(), name='user-notification'),


]

configurations/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    re_path(r'^$', RedirectView.as_view(url='/Chamado/')),
    path('Chamado/', include('accounts.urls')), 
    path('Chamado/', include('solicitation.urls')), 
    path('Chamado/', include('administration.urls')), 
    path('Chamado/', include('help_pages.urls')), 
    path('Chamado/', include('notifications.urls')), 
    path('Administracao-Chamado-DP-TI/', admin.site.urls),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

help_pages/urls.py
from django.urls import path
from help_pages import views

app_name = 'help_pages'

urlpatterns = [
    path('Ajuda/Adicionar/', views.blog_create, name='blog_create'),  
    path('Ajuda/Atualizar/<slug:SlugBlog>', views.blog_update, name='blog_update'),  
    path('Ajuda/Duvidas-Frequentes/', views.blog_fac, name='blog_fac'),  
    path('Ajuda/Modelos-De-Chamado/', views.blog_modelos, name='blog_modelos'),  
    path('Ajuda/Tutoriais/', views.blog_tutoriais, name='blog_tutoriais'),
    
    path('Ajuda/Notificacoes/<int:id>/Post/<slug:SlugBlog>/', views.blog_details, name='blog_details'),
    path('Ajuda/Notificacoes/<int:notification_pk>/Post/<slug:SlugBlog>/', views.BlogNotification.as_view(), name='blog-notification'),
 
]

htmxurls = [
    path('Ajuda/Duvidas-Frequentes/Like/<int:id>/Post/<slug:SlugBlog>/', views.like, name='like'),
    path('Ajuda/Duvidas-Frequentes/Details/Like/<int:id>/Post/<slug:SlugBlog>/', views.like_details, name='like_details'),
]

urlpatterns += htmxurls

notifications/urls.py
from django.urls import path
from notifications import views  


app_name = 'notifications'

urlpatterns = [
    path('Notificacoes/<int:notification_pk>/Solicitacao/<int:id>', views.PostNotification.as_view(), name='post-notification'),
    path('Notificacoes/Minhas-Notificacoes/', views.list_notifications, name='list_notifications'),
    path('Notificacoes/Minhas-Notificacoes/Partials', views.partial_notifications, name='partial_notifications'),
    
    path('Notificacoes/Minhas-Notificacoes/Arquivadas/', views.list_notifications_archive, name='list_notifications_archive'),
    path('Notificacoes/Minhas-Notificacoes/Partials/Arquivadas', views.partial_notifications_archive, name='partial_notifications_archive'),

    path('Notificacoes/Minhas-Notificacoes/Marcar-Como-Lida/<int:notification_pk>/', views.mark_as_read, name='mark_as_read'),
    path('Notificacoes/Minhas-Notificacoes/Marcar-Como-Nao-Lida/<int:notification_pk>/', views.mark_as_unread, name='mark_as_unread'),
    path('Notificacoes/Minhas-Notificacoes/Marcar-Todas-Como-Lidas/', views.mark_all_read, name='mark_all_read'),

    path('Notificacoes/Minhas-Notificacoes/Arquivar-Notificacao/<int:notification_pk>/', views.mark_archive, name='mark_archive'),
    path('Notificacoes/Minhas-Notificacoes/Marcar-Todas-Como-Arquivadas/', views.mark_all_archive, name='mark_all_archive'),

    path('Notificacoes/Minhas-Notificacoes/Desarquivar-Notificacao/<int:notification_pk>/', views.mark_unarchive, name='mark_unarchive'),
    path('Notificacoes/Minhas-Notificacoes/Marcar-Todas-Como-Desarquivadas/', views.mark_all_unarchive, name='mark_all_unarchive'),

    path('Notificacoes/Minhas-Notificacoes/Deletar-Notificacao/<int:notification_pk>/', views.delete_notification, name='delete_notification'),
    path('Notificacoes/Minhas-Notificacoes/Deletar-Notificacao/Arquivada/<int:notification_pk>/', views.delete_notification_achive, name='delete_notification_achive'),
    path('Notificacoes/Minhas-Notificacoes/Deletar-Todas-Notificacoes/', views.delete_all_notifications, name='delete_all_notifications'),
    path('Notificacoes/Minhas-Notificacoes/Deletar-Todas-Notificacoes/Arquivadas/', views.delete_all_archive, name='delete_all_archive'),
]

notifications/views.py
from django.db.models import Count, Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views import View
from django.core.paginator import Paginator
from django.contrib import messages

from django.utils import timezone
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required

from notifications.models import Notification
from solicitation.decorators import complete_tutorial
from solicitation.models import Solicitacoes

class PostNotification(View):
    def get(self, request, notification_pk, id, *args, **kwargs):
        notification = Notification.objects.get(pk=notification_pk)

        notification.user_has_seen = True
        if notification.DataVisualizacao == None:
            notification.DataVisualizacao = timezone.now()                        
        notification.save()


        if notification.TipoNotificacao_id == 7:
            solicitacao = Solicitacoes.objects.get(id=id)
            solicitacao = solicitacao.id
            for user in User.objects.filter(is_staff=True):
                    Notification.objects.create(
                        TipoNotificacao_id=13, from_user=request.user, to_user_id=user.id, to_admin=1, Solicitacao_id=solicitacao)
                
        if request.user.is_staff == True:
            return redirect('administration:admin_update_request',id=id)
        else:
            return redirect('solicitation:datails_requests', id=id)

@login_required
def list_notifications(request):
    template = 'notifications/base_notifications.html'

    user = request.user
    request_user = user.id
    query = Notification.objects.filter(to_user=user).order_by('-id')

    notifications = Notification.objects.filter(to_user=request_user).aggregate(
        total_notification=Count('id'),
        unchecked=Count('id', Q(user_has_seen=0)),
        checked=Count('id', Q(user_has_seen=1)),
        checkednotachive=Count('id', Q(user_has_seen=1, user_has_archive=0)),
        archived=Count('id', Q(user_has_seen=1, user_has_archive=1))
    )

    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)


    context = {
        'query':query,
        'notifications':notifications,
    }
    return render(request, template, context)

    
@login_required
def partial_notifications(request):
    template = 'notifications/partials/_list_notifications.html'

    user = request.user
    query = Notification.objects.filter(to_user=user).order_by('-id')    

    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)
    context = {
        'query':query
    }
    return render(request, template, context)


@login_required
def list_notifications_archive(request):
    template = 'notifications/base_notifications_archive.html'

    user = request.user
    request_user = user.id
    query = Notification.objects.filter(to_user=user, user_has_archive=1).order_by('-id')

    notifications = Notification.objects.filter(to_user=request_user).aggregate(
        total_notification=Count('id'),
        unchecked=Count('id', Q(user_has_seen=0)),
        checked=Count('id', Q(user_has_seen=1)),
        checkednotachive=Count('id', Q(user_has_seen=1, user_has_archive=0)),
        archived=Count('id', Q(user_has_seen=1, user_has_archive=1))
    )
    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)

    context = {
        'query':query,
        'notifications':notifications,
    }
    return render(request, template, context)

    
@login_required
def partial_notifications_archive(request):
    template = 'notifications/partials/_list_notifications_archive.html'

    user = request.user
    query = Notification.objects.filter(to_user=user).order_by('-id')    

    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)
    context = {
        'query':query
    }
    return render(request, template, context)


@login_required
def mark_as_read(request, notification_pk, *args, **kwargs): 
    notification = Notification.objects.get(pk=notification_pk)
    notification.user_has_seen = True
    if notification.DataVisualizacao == None:
        notification.DataVisualizacao = timezone.now()
    notification.save()    
    messages.success(
                    request, f'Notificação Marcada como Lida!'                         
                    )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def mark_as_unread(request, notification_pk, *args, **kwargs): 
    notification = Notification.objects.get(pk=notification_pk)
    notification.user_has_seen = False
    notification.save()
    messages.info(
                    request, f'Notificação Marcada como Não Lida!'                         
                    )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def mark_all_read(request, *args, **kwargs): 
    user = request.user
    count = Notification.objects.only('id').filter(to_user=user, user_has_seen=0).count()
    Notification.objects.filter(to_user=user, user_has_seen=0).exclude(TipoNotificacao_id=7).update(user_has_seen=1)
    Notification.objects.filter(DataVisualizacao=None).exclude(TipoNotificacao_id=7).update(DataVisualizacao=timezone.now())
    messages.info(
                    request, f'{count} Notificações Marcadas como Lidas!'                         
                    )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def mark_archive(request, notification_pk, *args, **kwargs):
    template_name = 'notifications/list_notifications.html'
    if request.method == "POST":
        user = request.user
    notification = Notification.objects.get(pk=notification_pk)
    notification.user_has_archive = True
    notification.save()
    messages.success(
                    request, f'Notificação Arquivada!'                         
                    )
    request_user = user.id
    query = Notification.objects.filter(to_user=user).order_by('-id')

    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)
    notifications = Notification.objects.filter(to_user=request_user).aggregate(
        total_notification=Count('id'),
        unchecked=Count('id', Q(user_has_seen=0)),
        checked=Count('id', Q(user_has_seen=1)),
        checkednotachive=Count('id', Q(user_has_seen=1, user_has_archive=0)),
        archived=Count('id', Q(user_has_seen=1, user_has_archive=1))
    )

    context = {
        'query':query,
        'notifications':notifications,
    }
    return render(request, template_name, context)


@login_required
def mark_all_archive(request):
    template_name = 'notifications/list_notifications.html'
    if request.method == "POST":
        user = request.user
    count = Notification.objects.only('id').filter(to_user=user, user_has_seen=1, user_has_archive=0).count()
    Notification.objects.filter(to_user=user, user_has_seen=1, user_has_archive=0).update(user_has_archive=1)
    messages.warning(
                    request, f'{count} Notificações Arquivadas!'                         
                    )
    request_user = user.id
    query = Notification.objects.filter(to_user=user).order_by('-id')

    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)
    notifications = Notification.objects.filter(to_user=request_user).aggregate(
        total_notification=Count('id'),
        unchecked=Count('id', Q(user_has_seen=0)),
        checked=Count('id', Q(user_has_seen=1)),
        checkednotachive=Count('id', Q(user_has_seen=1, user_has_archive=0)),
        archived=Count('id', Q(user_has_seen=1, user_has_archive=1))
    )

    context = {
        'query':query,
        'notifications':notifications,
    }
    return render(request, template_name, context)

@login_required
def mark_unarchive(request, notification_pk, *args, **kwargs):
    template_name = 'notifications/list_notifications_archive.html'
    if request.method == "POST":
        user = request.user
    notification = Notification.objects.get(pk=notification_pk)
    notification.user_has_archive = False
    notification.save()
    messages.success(
                    request, f'Notificação Desarquivada!'                         
                    )
    request_user = user.id
    query = Notification.objects.filter(to_user=user).order_by('-id')

    notifications = Notification.objects.filter(to_user=request_user).aggregate(
        total_notification=Count('id'),
        unchecked=Count('id', Q(user_has_seen=0)),
        checked=Count('id', Q(user_has_seen=1)),
        checkednotachive=Count('id', Q(user_has_seen=1, user_has_archive=0)),
        archived=Count('id', Q(user_has_seen=1, user_has_archive=1))
    )
    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)

    context = {
        'query':query,
        'notifications':notifications,
    }
    return render(request, template_name, context)
    

@login_required
def mark_all_unarchive(request):
    template_name = 'notifications/list_notifications.html'
    if request.method == "POST":
        user = request.user
    count = Notification.objects.only('id').filter(to_user=user, user_has_archive=1).count()
    Notification.objects.filter(to_user=user, user_has_seen=1, user_has_archive=1).update(user_has_archive=0)
    messages.info(
                request, f'{count} Notificações Desarquivadas!'                         
                )
    request_user = user.id
    query = Notification.objects.filter(to_user=user).order_by('-id')

    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)

notifications/templates/notifications/partials/_popup_notification.html
<button class="btn btn-primary" id="abremodal" type="button" data-bs-toggle="modal" hidden data-bs-target="#staticBackdrop"></button>

<div class="modal fade" id="staticBackdrop" data-bs-keyboard="false" data-bs-backdrop="static" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable modal-lg mt-6" role="document">
    <div class="modal-content border-2 border-danger">
      <div class="position-absolute top-0 end-0 mt-3 me-3 z-index-1">
          <button class="btn-close btn btn-sm btn-circle d-flex flex-center transition-base" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
      <div class="modal-body p-0 ">         
        <div class="bg-light rounded-top-lg py-3 ps-4 pe-6">
          <h2 class="mb-1 text-danger text-center fw-bold" id="staticBackdropLabel">Você tem {{notifications.unchecked}} Notificaç{{ notifications.unchecked|pluralize:"ão,ões!"}} não Lid{{ notifications.unchecked|pluralize:"a,as"}}.</h2>
          <p class="fs--2 mb-0 text-center">
              <i>Esta janela aparecerá enquanto houver Notificações não visualizadas.</i>
            </p>
          <p class="fs--2 mb-0 fw-bold text-center">
              <i>Verifique as Notificações para saber como anda sua Solicitação!.</i>
            </p>
          <div class="col-sm-auto text-end fs--2 mt-3">
            {% if notifications.total_notifications != 0%}

            {% if messages %}
          <hr>
            {% for message in messages %}
              <div class="card mb-3 {{ message.tags }}">
                <div class="card-body {{ message.tags }}">
                  <div class="row justify-content-between align-items-center">
                    <div class="col-md">
                      <h5 class="mb-2 mb-md-0 text-center {% if message.tags %} {{ message.tags }} {% endif %} "> 
                        {{ message }}                  
                      <span class="ms-1 far fa-check-circle" data-fa-transform="shrink-2"></span>
                      </h5>
                    </div>        
                  </div>
                </div>
              </div>
            {% endfor %}
          {% endif %}

            <p class="mb-1 mb-md-0 float-start fs--1" style="display:inline">
              Notificações - {{notifications.total_notifications}} |
              <a href="{% url 'notifications:list_notifications' %}"> 
              <strong class="text-danger">{{notifications.unchecked}} Não Lidas</strong>
              </a> |
              <a href="{% url 'notifications:list_notifications_archive' %}">
                <strong class="text-warning">{{notifications.archived}} Arquivadas</strong>
              </a>
            </p>
            
            <p class="mb-1 mb-md-0 btn btn-falcon-info btn-sm float-end fs--2 ms-2" style="display:inline">
              <a class="text-info" href="{% url 'notifications:mark_all_read' %}">Marcar todas como lidas</a>
            </p>
            <p class="mb-1 mb-md-0 btn btn-falcon-primary btn-sm float-end fs--2" style="display:inline">
              <a href="{% url 'notifications:list_notifications' %}">ver todas</a>
            </p>
            {% else %}
            {% endif %}            
          </div>
        </div>
        
        <div class="p-4">
          <div class="row">
            <div class="col-lg-12">
                {% for notification in query %}
                    {% if notification.user_has_archive == 0 %}
                        {% if notification.user_has_seen == 0 %}

                        <div class="hover-actions-trigger ">
                            <a class="border-bottom-0 notification rounded-0 border-x-0 border-300 notification-unread"  
                              {% if notification.Solicitacao.id %}
                                href="{% url 'notifications:post-notification' notification.id notification.Solicitacao.id %}"
                              {% elif notification.BlogPost.SlugBlog %}
                                href="{% url 'help_pages:blog-notification' notification.pk  notification.BlogPost.SlugBlog|title %}"
                              {% elif notification.NovoUser.id %}
                                href="{% url 'accounts:user-notification' notification.id notification.NovoUser.id %}"
                              {% endif %}
                              >  
                              <div class="notification-avatar text-center align-self-center">
                                <div class="avatar avatar-xl me-3">
                                  <span class="align-middle text-center mb-0 me-3 fs-3 fas fa-check-double text-secondary"></span>
                                </div>
                              </div> 
                              <div class="notification-body">
                                <p class="mb-1">        
                                
                                  <span class="fw-bold font-sans-serif">{{notification.from_user.first_name}} {{notification.from_user.last_name}}</span>
                                  {% if notification.TipoNotificacao_id == 1 %}
                                    <strong class="badge rounded-pill bg-success fs--2">{{notification.TipoNotificacao|upper}}:</strong> 
                                  {% elif notification.TipoNotificacao_id == 2 %}
                                      <strong class="badge rounded-pill bg-warning fs--2">{{notification.TipoNotificacao|upper}}:</strong>
                                  {% elif notification.TipoNotificacao_id == 3 %}
                                      <strong class="badge rounded-pill bg-danger fs--2">{{notification.TipoNotificacao|upper}}:</strong>
                                  {% elif notification.TipoNotificacao_id == 4 %}
                                    <strong class="badge rounded-pill bg-primary fs--2">{{notification.TipoNotificacao|upper}}:</strong>
                                  {% elif notification.TipoNotificacao_id == 5 %}
                                    <strong class="badge rounded-pill bg-success fs--2">{{notification.TipoNotificacao|upper}}:</strong>
                                  {% elif notification.TipoNotificacao_id == 6 %}
                                    <strong class="badge rounded-pill bg-info fs--2">{{notification.TipoNotificacao|upper}}:</strong>
                                  {% elif notification.TipoNotificacao_id == 7 %}
                                    <strong class="badge rounded-pill bg-dark fs--2">{{notification.TipoNotificacao|upper}}:</strong>
                                  {% elif notification.TipoNotificacao_id == 8 %}
                                    <strong class="badge rounded-pill bg-dark fs--2">{{notification.TipoNotificacao|upper}}:</strong>
                                    {% elif notification.TipoNotificacao_id == 9 %}
                                    <strong class="badge rounded-pill bg-info fs--2">{{notification.TipoNotificacao|upper}}:</strong>
                                  {% elif notification.TipoNotificacao_id == 11 %}
                                    <strong class="badge rounded-pill badge-soft-success fs--2">{{notification.TipoNotificacao|upper}}</strong>
                                  {% elif notification.TipoNotificacao_id == 12 %}
                                    <strong class="badge rounded-pill bg-info fs--2">{{notification.TipoNotificacao|upper}}:</strong>
                                  {% endif %}          
                                  
                                  {% if notification.BlogPost != None %}
                                  <p>{{notification.BlogPost}}</p>
                                  {% endif %}
                                  {% if notification.Solicitacao != None %}
                                  <p><b>Titulo do Chamado: </b>{{notification.Solicitacao.TituloDaSolicitacao}}</p> 
                                  <span class="text-end">            
                                    {% if notification.Solicitacao.StatusAtual_id == 1 %}
                                        <span class="text-end badge bg-danger fs-1 fw-bold">PENDENTE</span>
                                      {% elif notification.Solicitacao.StatusAtual_id == 2 %}
                                        <span class="text-end badge bg-warning fs-1 fw-bold">EM ANÁLISE</span>
                                      {% elif notification.Solicitacao.StatusAtual_id == 3 %}
                                        <span class="text-end badge bg-success fs-1 fw-bold">RESOLVIDO</span>
                                      {% elif  notification.Solicitacao.StatusAtual_id == 4 %}
                                        <span class="text-end badge bg-info fs-1 fw-bold">RESOLVIDO E FECHADO</span>
                                      {% elif notification.Solicitacao.StatusAtual_id == 5 %}
                                        <span class="text-end badge bg-secondary fs-1 fw-bold">REABERTO</span>
                                      {% else %}
                                    {% endif %}            
                                  </span>                                             
                                  {% endif %} 
                                  {% if notification.RespostaAdmin  != None %}
                                  <p>{{notification.RespostaAdmin|safe}}</p>
                                  {% endif %} 
                                  {% if notification.RespostaUser != None %}
                                  <p>{{notification.RespostaUser|safe}}</p>
                                  {% endif %}  
                                </p>
                    
                                  <span class="notification-time mb-0">
                                    <span class=" mb-0 fs--1 far fa-clock text-secondary"></span>
                                    {{notification.whenpublished}}
                                  </span>
                    
                                  <span class="fs-0">
                                    {% if notification.Solicitacao.id %}
                                      <span class="fw-bold">
                                        <span class="badge badge-soft-dark text-end">Chamado N°: {{notification.Solicitacao.id}}</span>
                                      </span>
                                    {% elif notification.BlogPost.id %}
                                      <span class="fw-bold">
                                        <span class="badge badge-soft-info text-end">Postagem: {{notification.BlogPost.CategoriaBlog}}</span>
                                      </span>
                                    {% endif %}
                                  </span> 
                                  
                                </div>                                          
                            </a> 
                            <div class="btn-group z-index-2 hover-actions end-0 me-3 position-absolute bottom-50 end-0">
                              {% if notification.TipoNotificacao_id == 7 %}
                              <a 
                                class="btn btn-light fs--2 z-index-10" type="button"             
                                href="{% url 'notifications:post-notification' notification.id notification.Solicitacao.id %}"
                                >          
                                <span class="fas fa-envelope-open-text"></span>
                                 Ir para Resposta
                              </a>          
                              {% else %}          
                              <a 
                                class="btn btn-light fs--2 z-index-10" type="button"             
                                href="{% url 'notifications:mark_as_read' notification.id %}"
                                >          
                                <span class="fas fa-envelope-open"></span>
                                 Marcar como lida
                              </a>
                              {% endif %}        
                            </div>
                          </div>
                        {% endif %}  
                    {% endif %}  
                {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>