accounts/urls.py
from django.urls import path
from accounts import views
from accounts import views as accounts_view


app_name = 'accounts'

urlpatterns = [

    # path('login', accounts_view.user_login, name='login'),
    path('Contas/Login', accounts_view.user_authentication, name='login'),
    path('Contas/Logout', accounts_view.user_logout, name='logout'),   
    path('Contas/Lock-screen', views.lock_screen, name='lock-screen'),

    path('Contas/Novo-Usuario/<int:notification_pk>/User-ID/<int:id>/', views.UserNotification.as_view(), name='user-notification'),


]

administration/urls.py
from django.urls import path
from administration import views

app_name = 'administration'

urlpatterns = [
    path('Administracao/Pendencias/', views.admin_list_request, name='admin_list_request'),
    path('Administracao/Em-Analise/', views.admin_list_analyse_request, name='admin_list_analyse_request'),
    path('Administracao/Finalizados/', views.admin_list_finished_request, name='admin_list_finished_request'),
    path('Administracao/Pendencias/Responder/Chamado-N-<int:id>', views.admin_update_request, name='admin_update_request'),
    path('Administracao/Chamados-Antigos/', views.admin_list_chamados_antigos, name='admin_list_chamados_antigos'),
    path('Administracao/Chamados-Antigos/Detalhes/Chamado-N-<int:id>', views.admin_details_chamados_antigos, name='admin_details_chamados_antigos'),  
    path('Administracao/Auditoria/Logins/', views.admin_list_login_audit, name='admin_list_login_audit'),
    path('Administracao/Pesquisar/Resultados/', views.navbar_search, name='navbar_search'),
]

configurations/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    re_path(r'^$', RedirectView.as_view(url='/Chamado/')),
    path('Chamado/', include('accounts.urls')), 
    path('Chamado/', include('solicitation.urls')), 
    path('Chamado/', include('administration.urls')), 
    path('Chamado/', include('help_pages.urls')), 
    path('Chamado/', include('notifications.urls')), 
    path('Administracao-Chamado-DP-TI/', admin.site.urls),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

help_pages/urls.py
from django.urls import path
from help_pages import views

app_name = 'help_pages'

urlpatterns = [
    path('Ajuda/Adicionar/', views.blog_create, name='blog_create'),  
    path('Ajuda/Atualizar/<slug:SlugBlog>', views.blog_update, name='blog_update'),  
    path('Ajuda/Duvidas-Frequentes/', views.blog_fac, name='blog_fac'),  
    path('Ajuda/Modelos-De-Chamado/', views.blog_modelos, name='blog_modelos'),  
    path('Ajuda/Tutoriais/', views.blog_tutoriais, name='blog_tutoriais'),
    
    path('Ajuda/Notificacoes/<int:id>/Post/<slug:SlugBlog>/', views.blog_details, name='blog_details'),
    path('Ajuda/Notificacoes/<int:notification_pk>/Post/<slug:SlugBlog>/', views.BlogNotification.as_view(), name='blog-notification'),
 
]

htmxurls = [
    path('Ajuda/Duvidas-Frequentes/Like/<int:id>/Post/<slug:SlugBlog>/', views.like, name='like'),
    path('Ajuda/Duvidas-Frequentes/Details/Like/<int:id>/Post/<slug:SlugBlog>/', views.like_details, name='like_details'),
]

urlpatterns += htmxurls

solicitation/urls.py
from django.urls import path
from solicitation import views

app_name = 'solicitation'

urlpatterns = [
    path('', views.index, name='index'),
    path('Solicitar/', views.make_request, name='make_request'),
    path('Meus-Chamados/', views.user_list_request, name='user_list_request'),
    path('Meus-Chamados/Detalhes/Chamado-N-<int:id>', views.details_request, name='datails_requests'),  
    path('Meus-Chamados/Editar/Chamado-N-<int:id>', views.update_request, name='update_request'), 
]

solicitation/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, redirect, render
from help_pages.models import ChamadoBlog
from notifications.models import Notification

from solicitation.decorators import complete_tutorial
from solicitation.forms import (RespostaUsuarioForm, SerResponsavelForm,
                                SolicitacoesForm, SolicitacoesUpdateForm)
from solicitation.models import (RespostaSolicitacao, RespostaUsuario,
                                 Solicitacoes)


@login_required
def index(request):
    template_name = 'solicitation/index.html'
    re = request.session['re']

    dashboard = Solicitacoes.objects.only('id').filter(
        ReSolicitante=re).aggregate(
        analise=Count('id', Q(StatusAtual=2)),
        resolvidos=Count('id', Q(StatusAtual__in=(3, 4))),
        pendentes=Count('id', Q(StatusAtual__in=(1, 5)))
    )

    admindash = Solicitacoes.objects.only('id').all().aggregate(
        analise=Count('id', Q(StatusAtual=2)),
        resolvidos=Count('id', Q(StatusAtual__in=(3, 4))),
        pendentes=Count('id', Q(StatusAtual__in=(1, 5)))
    )
  
    request_user = request.user
    users_notification = Notification.objects.filter(to_user=request_user, user_has_seen=0, user_has_archive=0).only('id').exists()   

    context = {          
        #USER SECTION
        'dashboard': dashboard,
        'admindash': admindash,
        'users_notification': users_notification
    }
    return render(request, template_name, context)

@login_required
def make_request(request):
    template_name = 'solicitation/make_request.html'
    
    request_user = request.user
    users_notification = Notification.objects.filter(to_user=request_user, user_has_seen=0, user_has_archive=0).only('id').exists() 

    form = SolicitacoesForm(
        request.POST or None,
        request.FILES or None
    )
    if request.method == "POST":
        if form.is_valid():
            data = form.save(commit=False)
            data.PostoGradSolicitante = request.POST.get('nposto')
            data.ReSolicitante = request.POST['nre']
            data.NomeGuerraSolicitante = request.POST['nnomeguerra']
            data.CpfSolicitante = request.POST['ncpf']
            data.FuncaoSolicitante = request.POST['nfuncao']
            data.CodOpmSolicitante = request.POST['nopmcod']
            data.GrandeComandoSolicitante = request.POST['nopmcod1']
            data.UnidadeSolicitante = request.POST['nopmcod2']
            data.DepartamentoSolicitante = request.POST['nopmcod3']
            data.DivisaoSolicitante = request.POST['nopmcod4']
            data.SecaoSolicitante = request.POST['nopmcod5']
            data.save()

            for user in User.objects.filter(is_staff=True):            
                Notification.objects.create(
                    TipoNotificacao_id=1, from_user=request.user, to_user_id=user.id, to_admin=1, Solicitacao_id=data.id)                

            messages.success(
                request,
                f'Solicitação realizada com sucesso'
            )
        return redirect('solicitation:user_list_request')

    context = {
        'form': form,
        'users_notification': users_notification,
    }
    return render(request, template_name, context)

@login_required
def details_request(request, id):
    template_name = 'solicitation/details_request.html'

    request_user = request.user
    users_notification = Notification.objects.filter(to_user=request_user, user_has_seen=0, user_has_archive=0).only('id').exists() 

    username = request.user.username
    obj = Solicitacoes.objects.get(id=id)
    his = Solicitacoes.Historico.all().filter(id=id).order_by('history_date')

    if obj.DataDoEncerramento == None:
        tempo_atendimento = '24 Horas'
    else:
        tempo_atendimento = obj.DataDoEncerramento - obj.DataDaSolicitacao
        tempo_atendimento = str(tempo_atendimento).split(".")[0]

    respostas = RespostaSolicitacao.objects.select_related(
        'RespostaResponsavel').select_related(
            'Solicitacao').filter(
        Solicitacao=obj.id).order_by('RespostaData')


    respostasUsuarios = RespostaUsuario.objects.all().select_related(
        'RespostaUsuarioResponsavel').select_related(
            'RespostaDaSolicitacao')

    if request.user.is_authenticated and username != obj.CpfSolicitante:
        return redirect('solicitation:user_list_request')

    form_resposta_user = RespostaUsuarioForm(request.POST or None)
    if request.method == "POST" and 'resposta_user' in request.POST:
        resposta_user_id = int(request.POST.get('resposta_id'))
        respostaSolicitacaoid = RespostaSolicitacao.objects.get(
            id=resposta_user_id)

        if form_resposta_user.is_valid():
            add_resposta_user = form_resposta_user.save(commit=False)
            add_resposta_user.RespostaUsuarioResponsavel_id = request.user.id
            add_resposta_user.RespostaDaSolicitacao_id = respostaSolicitacaoid.id
            add_resposta_user.save()

            solicitante = obj.CpfSolicitante
            solicitante_user = User.objects.get(username=solicitante)
            resposta = RespostaUsuario.objects.last().id    
            responsavel = obj.Responsavel  
            
            Notification.objects.create(
            TipoNotificacao_id=8, from_user=solicitante_user, to_user=responsavel, to_admin=1, Solicitacao_id=id, RespostaUser_id=resposta)

            return redirect('solicitation:datails_requests', id=id)

    form = SerResponsavelForm(request.POST or None, instance=obj)
    if request.method == "POST" and 'resolvidoo' in request.POST:
        if form.is_valid():
            add_status = form.save(commit=False)
            add_status.Responsavel_id = request.user.id
            add_status.StatusAtual_id = 3
            add_status.save()

            solicitacao = Solicitacoes.objects.first().id

            for user in User.objects.filter(is_staff=True):            
                Notification.objects.create(
                    TipoNotificacao_id=10, from_user=request.user, to_user_id=user.id, to_admin=1, Solicitacao_id=solicitacao)            
            
        return redirect('solicitation:datails_requests', id=id)

    try:
        notificationid = Notification.objects.get(TipoNotificacao_id=7, Solicitacao_id=id)
        getrespostaid = notificationid.RespostaAdmin_id
        visualizou_a_resposta = Notification.objects.get(TipoNotificacao_id=7, RespostaAdmin_id=getrespostaid)
        verificaresposta = RespostaSolicitacao.objects.get(
        Solicitacao_id=id).id 
    except:
        visualizou_a_resposta = None
        verificaresposta = None

    ultimostatus = obj.StatusAtual

    ultres = None
    testeultres = RespostaSolicitacao.objects.only('id').filter(Solicitacao=obj.id).exists()
    if testeultres == False:
        ultres = False
    else:
        ultres = RespostaSolicitacao.objects.filter(
            Solicitacao=obj.id).order_by("-id")[0]

    re = request.session['re']
    dashboard = Solicitacoes.objects.only('id').filter(
        ReSolicitante=re).aggregate(
        analise=Count('id', Q(StatusAtual=2)),
        resolvidos=Count('id', Q(StatusAtual__in=(3, 4))),
        pendentes=Count('id', Q(StatusAtual__in=(1, 5)))
    )

    respostaresponsavel = None
    try:
        respostaresponsavel = RespostaSolicitacao.objects.get(Solicitacao=id)
    except:
        respostaresponsavel


    if obj.DataDoEncerramento == None:
        tempo_atendimento = '24 Horas'
        dias = 0
        horas = 0
        minutos = 0
    else:
        tempo_atendimento = obj.DataDoEncerramento - obj.DataDaSolicitacao
        tempo_atendimento = tempo_atendimento.seconds 
        dias, tempo_atendimento = divmod(tempo_atendimento, 86400)
        horas, tempo_atendimento = divmod(tempo_atendimento, 3600)
        minutos, tempo_atendimento = divmod(tempo_atendimento, 60)

    context = {
        'details': obj,
        'historico': his,
        'respostas': respostas,
        'respostaresponsavel': respostaresponsavel,
        'form_resposta_user': form_resposta_user,
        'respostasUsuarios': respostasUsuarios,
        'tempo_atendimento': tempo_atendimento,
        'ultimostatus': ultimostatus,
        'visualizou_a_resposta': visualizou_a_resposta,
        'verificaresposta': verificaresposta,
        'dia': dias,
        'hora': horas,
        'minuto': minutos,
        'segundo': tempo_atendimento,    
        'users_notification': users_notification,    

        'ultres': ultres,
        # DASH
        'dashboard': dashboard,


    }
    return render(request, template_name, context)

@login_required
def update_request(request, id):
    template_name = 'solicitation/update_request.html'
    obj = get_object_or_404(Solicitacoes, id=id)

    request_user = request.user
    users_notification = Notification.objects.filter(to_user=request_user, user_has_seen=0, user_has_archive=0).only('id').exists() 

    username = request.user.username

    if request.user.is_authenticated and username != obj.CpfSolicitante:
        return redirect('solicitation:user_list_request')

    form = SolicitacoesUpdateForm(request.POST or None, request.FILES or None, instance=obj)
    if form.is_valid():
        add_user = form.save(commit=False)
        add_user.usuario_id = request.user.id
        add_user.save()

        return redirect('solicitation:user_list_request')

    context = {
        'form': form,
        'users_notification': users_notification,
    }
    return render(request, template_name, context)

@login_required
def user_list_request(request):
    template_name = 'solicitation/user_list_requests.html'

    request_user = request.user

solicitation/templates/solicitation/index.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
{% load _counters %}
{% load _popup_notification %}

<div class="row">
	{% if request.user.is_staff %}		 
		{% admin_counters %}
		<div class="col-12">
			<hr>
			<div class="row g-3 mb-3 ">
				{% if admindash.pendentes != 0 %}
				<div class="col-sm-6 col-md-4">
					<a class="link-danger box-hover d-block" name="cpendencias" id="cpendencias" href="{% url 'administration:admin_list_request' %}">
						<div class="card overflow-hidden" style="min-width: 12rem">
							<div class="bg-holder bg-card" style="background-image:url({% static 'img/icons/spot-illustrations/corner-1.png' %});"></div>
							<!--/.bg-holder-->
							<div class="card-body position-relative text-center">	
								<div class="display-2 fs-2 fw-bold fa-bounce font-sans-serif text-danger">Pendências - {{ admindash.pendentes }}
								</div>
							</div>
						</div>
					</a>
				</div>
				{% else %}
				<div class="col-sm-6 col-md-4">
					<a class="link-success box-hover d-block" href="{% url 'administration:admin_list_request' %}">
						<div class="card overflow-hidden" style="min-width: 12rem">
							<div class="bg-holder bg-card" style="background-image:url({% static 'img/icons/spot-illustrations/corner-3.png'%});"></div>
							<!--/.bg-holder-->
							<div class="card-body position-relative">
								<div class="display-2 fs-2 fw-bold text-center font-sans-serif text-success">Não há Pendências
								</div> 
							</div>
						</div>
					</a>
					</div>
				{% endif %}
				<div class="col-sm-6 col-md-4">
					<a class="link-warning box-hover d-block" name="canalise" id="canalise" href="{% url 'administration:admin_list_analyse_request' %}">
						<div class="card overflow-hidden" style="min-width: 12rem">
							<div class="bg-holder bg-card" style="background-image:url({% static 'img/icons/spot-illustrations/corner-2.png'%});"></div>
							<!--/.bg-holder-->
							<div class="card-body position-relative">		
								<div class="display-2 fs-2 fw-bold text-center font-sans-serif text-warning" >Análise - {{ admindash.analise }}
								</div>
							</div>
						</div>
					</a>
				</div>
				
				<div class="col-sm-6 col-md-4">
				<a class="link-success box-hover d-block" href="{% url 'administration:admin_list_finished_request' %}">
					<div class="card overflow-hidden" style="min-width: 12rem">
						<div class="bg-holder bg-card" style="background-image:url({% static 'img/icons/spot-illustrations/corner-3.png'%});"></div>
						<!--/.bg-holder-->
						<div class="card-body position-relative">
							<div class="display-2 fs-2 fw-bold text-center font-sans-serif text-success">Resolvidos
							</div> 
						</div>
					</div>
				</a>
				</div>
				
				<div class="col-12">
					<a class="link-dark box-hover d-block" href="{% url 'administration:admin_list_login_audit' %}">
						<div class="card overflow-hidden" style="min-width: 12rem">
							<div class="bg-holder bg-card" style="background-image:url({% static 'img/icons/spot-illustrations/corner-5.png'%});"></div>
							<!--/.bg-holder-->
							<div class="card-body position-relative">		
								<div class="display-2 fs-2 fw-normal text-center font-sans-serif text-dark">Aditoria Login de Usuários
								</div> 
							</div>
						</div>
					</a>
				</div>
			</div>	
			<hr>
			<div class="row">
				<div class="col-sm-12 col-sm-6 col-md-6">
					<a class="link-success box-hover d-block" href="{% url 'solicitation:make_request' %}">
						<div class="card overflow-hidden" style="min-width: 12rem">
							<div class="bg-holder bg-card" style="background-image:url({% static 'img/icons/spot-illustrations/corner-3.png' %});"></div>
							<!--/.bg-holder-->
							<div class="card-body position-relative">					
	
								<div class="display-2 fs-2 fw-normal text-center font-sans-serif text-success" >Solicitar Chamado <i class="fas fa-plus-circle"> </i></div>
							</div>
						</div>
					</a>
				</div>
				<div class="col-sm-12 col-sm-6 col-md-6">
					<a class="link-primary box-hover d-block" href="{% url 'solicitation:user_list_request' %}">
						<div class="card overflow-hidden" style="min-width: 12rem">
							<div class="bg-holder bg-card" style="background-image:url({% static 'img/icons/spot-illustrations/corner-2.png'%});"></div>
							<!--/.bg-holder-->
							<div class="card-body position-relative">
	
								<div class="display-2 fs-2 fw-normal text-center font-sans-serif text-info" >Minhas Solicitações <i class="far fa-list-alt"> </i></div>
							</div>
						</div>
					</a>
				</div>				
			</div>	
	</div>
	{% endif %}
</div>	

{% if messages %}
	{% for message in messages%}
		<div {% if message.tags %} class="alert {{ message.tags }} {% endif %} border-2 d-flex align-items-center" role="alert">
			<p class="mb-0 fs-1 text-center flex-1">{{ message}}</p>
			<button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	{% endfor %}
{% endif %}	

{% if not request.user.is_staff and not request.user.is_admin  %}
	<div class="row">
		<div class="col-xl-12 col-lg-12 col-md-12">
			<div class="card bg-transparent-50 overflow-hidden">
				<div class="card-header position-relative">
					<div class="bg-holder d-none d-md-block bg-card z-index-1" style="background-image:url({% static 'img/icons/spot-illustrations/corner-4.png'%});background-position:right bottom;z-index:-1;"></div>
					<!--/.bg-holder-->
						<div class="position-relative text-center z-index-2">
							<div>
								<h3 class="text-primary mb-1">Olá, 
									{{ request.session.postoo }} 
									{{ request.session.nomeguerra|title }}!</h3>
									<h3 class="fw-light overflow-hidden"><span class="typed-text fw-bold ms-1" data-typed-text='["Aproveite o Sistema de Chamados.","Faça suas solicitações.","Acompanhe seus chamados.","Tire suas dúvidas!"]'></span></h3>
			
								<p> </p>
							
							<div class="d-flex py-3">
								<div class="row text-center fs-1">
									<div class="col-md-3 m-2">
										<p class=" badge rounded-pill badge-soft-danger">Pendentes</p>
										<h4 class=" text-center mb-0">{{ dashboard.pendentes }}</h4>
									</div>
									<div class="col-md-3 m-2">
										<p class=" badge rounded-pill badge-soft-warning">Em Análise</p>
										<h4 class=" text-center mb-0">{{ dashboard.analise }}</h4>
									</div>
									<div class="col-md-3 m-2">
										<p class=" badge rounded-pill badge-soft-success">Resolvidos</p>
										<h4 class=" text-center mb-0">{{ dashboard.resolvidos }}</h4>
									</div>	
								</div>							
							</div>
						</div>					
					</div>
				</div>
			</div>			
			<hr>
			<div class="row g-3 mb-2">
				<div class="col-sm-12 col-md-6 col-lg-6">
					<a class="link-success box-hover d-block" href="{% url 'solicitation:make_request' %}">
						<div class="card overflow-hidden" style="min-width: 12rem">
							<div class="bg-holder bg-card" style="background-image:url({% static 'img/icons/spot-illustrations/corner-3.png' %});"></div>
							<!--/.bg-holder-->
							<div class="card-body position-relative">					

								<div class="display-2 fs-2 fw-normal text-center font-sans-serif text-success" >Solicitar Chamado <i class="fas fa-plus-circle"> </i></div>
							</div>
						</div>
					</a>
				</div>
				<div class="col-sm-12 col-md-6 col-lg-6">
					<a class="link-primary box-hover d-block" href="{% url 'solicitation:user_list_request' %}">
						<div class="card overflow-hidden" style="min-width: 12rem">
							<div class="bg-holder bg-card" style="background-image:url({% static 'img/icons/spot-illustrations/corner-2.png'%});"></div>
							<!--/.bg-holder-->
							<div class="card-body position-relative">

								<div class="display-2 fs-2 fw-normal text-center font-sans-serif text-info" >Minhas Solicitações <i class="far fa-list-alt"> </i></div>
							</div>
						</div>
					</a>
				</div>						
			</div>
			<hr> 
		</div>	
	</div>
	{% comment %} <div class="row">
		<div class="col-xl-9 col-lg-9 col-md-8 col-sm-12 mb-2">
			<p class="text-center fs-1 bg-light text-danger rounded fw-bold"> Novidades</p>
			<div class="swiper-container theme-slider" data-swiper='{"autoplay":true,"spaceBetween":5,"loop":true,"loopedSlides":6,"slideToClickedSlide":true,"speed":4000}'>
				<div class="swiper-wrapper">
					{% for n in novidades %}
						<div class="swiper-slide">
							<div class="card mb-3">
								<div class="bg-holder d-none d-lg-block bg-card" style="background-image:url({% static 'img/icons/spot-illustrations/corner-4.png' %});"></div>
								<div class="card-body position-relative">
									<div class="row">
										<div class="col-lg-8">
											<h4>{{ n.TituloBlog|upper }}</h4>
											<a class="btn btn-link ps-0 btn-sm" href="{% url 'help_pages:blog_details' n.id n.SlugBlog|title %}" target="_blank">Ver <span class="fas fa-chevron-right ms-1 fs--2"></span>
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
		<div class="col-xl-3 col-lg-3 col-md-4 col-sm-12 mb-4">
			<p class="text-center fs-1 bg-light rounded fw-bold"> Acesso Rápido</p>
			<div class="list-group fw-bold">
				<a class="list-group-item text-primary box-hover list-group-item-action" href="#">
					<div class="text-center">
						<span>Tutorial de instalação do SIPL</span>	
					</div>			
				</a>
				<a class="list-group-item box-hover list-group-item-action" href="#">
					<div class="text-center">
						<span>Arquivos do SIPL</span>	
					</div>			
				</a>
				<a class="list-group-item box-hover list-group-item-action" href="#">
					<div class="text-center">
						<span>Ultilidades</span>	
					</div>			
				</a>
			</div>
		</div>
	</div> {% endcomment %}
{% endif %}
	
{% popup_notification %}
{% block scripts %} 
	{% if users_notification and not request.user.is_superuser %}
		<script>
			document.querySelector('#abremodal').click();
		</script>
	{% endif %}
{% endblock scripts %}

{% endblock content %}