accounts/urls.py
from django.urls import path
from accounts import views
from accounts import views as accounts_view


app_name = 'accounts'

urlpatterns = [

    # path('login', accounts_view.user_login, name='login'),
    path('Contas/Login', accounts_view.user_authentication, name='login'),
    path('Contas/Logout', accounts_view.user_logout, name='logout'),   
    path('Contas/Lock-screen', views.lock_screen, name='lock-screen'),

    path('Contas/Novo-Usuario/<int:notification_pk>/User-ID/<int:id>/', views.UserNotification.as_view(), name='user-notification'),


]

configurations/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    re_path(r'^$', RedirectView.as_view(url='/Chamado/')),
    path('Chamado/', include('accounts.urls')), 
    path('Chamado/', include('solicitation.urls')), 
    path('Chamado/', include('administration.urls')), 
    path('Chamado/', include('help_pages.urls')), 
    path('Chamado/', include('notifications.urls')), 
    path('Administracao-Chamado-DP-TI/', admin.site.urls),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/urls.py
from django.urls import path
from notifications import views  


app_name = 'notifications'

urlpatterns = [
    path('Notificacoes/<int:notification_pk>/Solicitacao/<int:id>', views.PostNotification.as_view(), name='post-notification'),
    path('Notificacoes/Minhas-Notificacoes/', views.list_notifications, name='list_notifications'),
    path('Notificacoes/Minhas-Notificacoes/Partials', views.partial_notifications, name='partial_notifications'),
    
    path('Notificacoes/Minhas-Notificacoes/Arquivadas/', views.list_notifications_archive, name='list_notifications_archive'),
    path('Notificacoes/Minhas-Notificacoes/Partials/Arquivadas', views.partial_notifications_archive, name='partial_notifications_archive'),

    path('Notificacoes/Minhas-Notificacoes/Marcar-Como-Lida/<int:notification_pk>/', views.mark_as_read, name='mark_as_read'),
    path('Notificacoes/Minhas-Notificacoes/Marcar-Como-Nao-Lida/<int:notification_pk>/', views.mark_as_unread, name='mark_as_unread'),
    path('Notificacoes/Minhas-Notificacoes/Marcar-Todas-Como-Lidas/', views.mark_all_read, name='mark_all_read'),

    path('Notificacoes/Minhas-Notificacoes/Arquivar-Notificacao/<int:notification_pk>/', views.mark_archive, name='mark_archive'),
    path('Notificacoes/Minhas-Notificacoes/Marcar-Todas-Como-Arquivadas/', views.mark_all_archive, name='mark_all_archive'),

    path('Notificacoes/Minhas-Notificacoes/Desarquivar-Notificacao/<int:notification_pk>/', views.mark_unarchive, name='mark_unarchive'),
    path('Notificacoes/Minhas-Notificacoes/Marcar-Todas-Como-Desarquivadas/', views.mark_all_unarchive, name='mark_all_unarchive'),

    path('Notificacoes/Minhas-Notificacoes/Deletar-Notificacao/<int:notification_pk>/', views.delete_notification, name='delete_notification'),
    path('Notificacoes/Minhas-Notificacoes/Deletar-Notificacao/Arquivada/<int:notification_pk>/', views.delete_notification_achive, name='delete_notification_achive'),
    path('Notificacoes/Minhas-Notificacoes/Deletar-Todas-Notificacoes/', views.delete_all_notifications, name='delete_all_notifications'),
    path('Notificacoes/Minhas-Notificacoes/Deletar-Todas-Notificacoes/Arquivadas/', views.delete_all_archive, name='delete_all_archive'),
]

notifications/views.py
from django.db.models import Count, Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views import View
from django.core.paginator import Paginator
from django.contrib import messages

from django.utils import timezone
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required

from notifications.models import Notification
from solicitation.decorators import complete_tutorial
from solicitation.models import Solicitacoes

class PostNotification(View):
    def get(self, request, notification_pk, id, *args, **kwargs):
        notification = Notification.objects.get(pk=notification_pk)

        notification.user_has_seen = True
        if notification.DataVisualizacao == None:
            notification.DataVisualizacao = timezone.now()                        
        notification.save()


        if notification.TipoNotificacao_id == 7:
            solicitacao = Solicitacoes.objects.get(id=id)
            solicitacao = solicitacao.id
            for user in User.objects.filter(is_staff=True):
                    Notification.objects.create(
                        TipoNotificacao_id=13, from_user=request.user, to_user_id=user.id, to_admin=1, Solicitacao_id=solicitacao)
                
        if request.user.is_staff == True:
            return redirect('administration:admin_update_request',id=id)
        else:
            return redirect('solicitation:datails_requests', id=id)

@login_required
def list_notifications(request):
    template = 'notifications/base_notifications.html'

    user = request.user
    request_user = user.id
    query = Notification.objects.filter(to_user=user).order_by('-id')

    notifications = Notification.objects.filter(to_user=request_user).aggregate(
        total_notification=Count('id'),
        unchecked=Count('id', Q(user_has_seen=0)),
        checked=Count('id', Q(user_has_seen=1)),
        checkednotachive=Count('id', Q(user_has_seen=1, user_has_archive=0)),
        archived=Count('id', Q(user_has_seen=1, user_has_archive=1))
    )

    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)


    context = {
        'query':query,
        'notifications':notifications,
    }
    return render(request, template, context)

    
@login_required
def partial_notifications(request):
    template = 'notifications/partials/_list_notifications.html'

    user = request.user
    query = Notification.objects.filter(to_user=user).order_by('-id')    

    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)
    context = {
        'query':query
    }
    return render(request, template, context)


@login_required
def list_notifications_archive(request):
    template = 'notifications/base_notifications_archive.html'

    user = request.user
    request_user = user.id
    query = Notification.objects.filter(to_user=user, user_has_archive=1).order_by('-id')

    notifications = Notification.objects.filter(to_user=request_user).aggregate(
        total_notification=Count('id'),
        unchecked=Count('id', Q(user_has_seen=0)),
        checked=Count('id', Q(user_has_seen=1)),
        checkednotachive=Count('id', Q(user_has_seen=1, user_has_archive=0)),
        archived=Count('id', Q(user_has_seen=1, user_has_archive=1))
    )
    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)

    context = {
        'query':query,
        'notifications':notifications,
    }
    return render(request, template, context)

    
@login_required
def partial_notifications_archive(request):
    template = 'notifications/partials/_list_notifications_archive.html'

    user = request.user
    query = Notification.objects.filter(to_user=user).order_by('-id')    

    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)
    context = {
        'query':query
    }
    return render(request, template, context)


@login_required
def mark_as_read(request, notification_pk, *args, **kwargs): 
    notification = Notification.objects.get(pk=notification_pk)
    notification.user_has_seen = True
    if notification.DataVisualizacao == None:
        notification.DataVisualizacao = timezone.now()
    notification.save()    
    messages.success(
                    request, f'Notificação Marcada como Lida!'                         
                    )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def mark_as_unread(request, notification_pk, *args, **kwargs): 
    notification = Notification.objects.get(pk=notification_pk)
    notification.user_has_seen = False
    notification.save()
    messages.info(
                    request, f'Notificação Marcada como Não Lida!'                         
                    )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def mark_all_read(request, *args, **kwargs): 
    user = request.user
    count = Notification.objects.only('id').filter(to_user=user, user_has_seen=0).count()
    Notification.objects.filter(to_user=user, user_has_seen=0).exclude(TipoNotificacao_id=7).update(user_has_seen=1)
    Notification.objects.filter(DataVisualizacao=None).exclude(TipoNotificacao_id=7).update(DataVisualizacao=timezone.now())
    messages.info(
                    request, f'{count} Notificações Marcadas como Lidas!'                         
                    )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def mark_archive(request, notification_pk, *args, **kwargs):
    template_name = 'notifications/list_notifications.html'
    if request.method == "POST":
        user = request.user
    notification = Notification.objects.get(pk=notification_pk)
    notification.user_has_archive = True
    notification.save()
    messages.success(
                    request, f'Notificação Arquivada!'                         
                    )
    request_user = user.id
    query = Notification.objects.filter(to_user=user).order_by('-id')

    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)
    notifications = Notification.objects.filter(to_user=request_user).aggregate(
        total_notification=Count('id'),
        unchecked=Count('id', Q(user_has_seen=0)),
        checked=Count('id', Q(user_has_seen=1)),
        checkednotachive=Count('id', Q(user_has_seen=1, user_has_archive=0)),
        archived=Count('id', Q(user_has_seen=1, user_has_archive=1))
    )

    context = {
        'query':query,
        'notifications':notifications,
    }
    return render(request, template_name, context)


@login_required
def mark_all_archive(request):
    template_name = 'notifications/list_notifications.html'
    if request.method == "POST":
        user = request.user
    count = Notification.objects.only('id').filter(to_user=user, user_has_seen=1, user_has_archive=0).count()
    Notification.objects.filter(to_user=user, user_has_seen=1, user_has_archive=0).update(user_has_archive=1)
    messages.warning(
                    request, f'{count} Notificações Arquivadas!'                         
                    )
    request_user = user.id
    query = Notification.objects.filter(to_user=user).order_by('-id')

    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)
    notifications = Notification.objects.filter(to_user=request_user).aggregate(
        total_notification=Count('id'),
        unchecked=Count('id', Q(user_has_seen=0)),
        checked=Count('id', Q(user_has_seen=1)),
        checkednotachive=Count('id', Q(user_has_seen=1, user_has_archive=0)),
        archived=Count('id', Q(user_has_seen=1, user_has_archive=1))
    )

    context = {
        'query':query,
        'notifications':notifications,
    }
    return render(request, template_name, context)

@login_required
def mark_unarchive(request, notification_pk, *args, **kwargs):
    template_name = 'notifications/list_notifications_archive.html'
    if request.method == "POST":
        user = request.user
    notification = Notification.objects.get(pk=notification_pk)
    notification.user_has_archive = False
    notification.save()
    messages.success(
                    request, f'Notificação Desarquivada!'                         
                    )
    request_user = user.id
    query = Notification.objects.filter(to_user=user).order_by('-id')

    notifications = Notification.objects.filter(to_user=request_user).aggregate(
        total_notification=Count('id'),
        unchecked=Count('id', Q(user_has_seen=0)),
        checked=Count('id', Q(user_has_seen=1)),
        checkednotachive=Count('id', Q(user_has_seen=1, user_has_archive=0)),
        archived=Count('id', Q(user_has_seen=1, user_has_archive=1))
    )
    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)

    context = {
        'query':query,
        'notifications':notifications,
    }
    return render(request, template_name, context)
    

@login_required
def mark_all_unarchive(request):
    template_name = 'notifications/list_notifications.html'
    if request.method == "POST":
        user = request.user
    count = Notification.objects.only('id').filter(to_user=user, user_has_archive=1).count()
    Notification.objects.filter(to_user=user, user_has_seen=1, user_has_archive=1).update(user_has_archive=0)
    messages.info(
                request, f'{count} Notificações Desarquivadas!'                         
                )
    request_user = user.id
    query = Notification.objects.filter(to_user=user).order_by('-id')

    query = Paginator(query, 20)

    page_number = request.GET.get('page')
    query = query.get_page(page_number)

notifications/templates/notifications/base_notifications.html
{% extends 'base.html' %}
{% block title %}
    Chamado | Notificações
{% endblock title %}
{% load static %} 
{% block content %}

{% include 'notifications/list_notifications.html' %}

{% endblock %}

notifications/templates/notifications/base_notifications_archive.html
{% extends 'base.html' %}
{% block title %}
    Chamado | Arquivadas
{% endblock title %}
{% load static %} 
{% block content %}

{% include 'notifications/list_notifications_archive.html' %}

{% endblock %}

notifications/templates/notifications/list_notifications.html
<div id="list_partial">
  <p>
    <h4 class="text-center">Caixa de Entrada</h4>
  </p>

  <div class="card overflow-hidden mb-3">
    <div class="card-header bg-light" >
      <div class="row flex-between-center">
        <div class="col-6 text-start mt-0">
          <a class="btn btn-falcon-warning btn-sm font-sans-serif fs--2" href="{% url 'notifications:list_notifications_archive' %}">Ver notificações Arquivadas</a>

          <h6 class="mb-1 mb-md-0 mt-2">
            Notificações - {{notifications.total_notification}} | 
            <strong class="text-danger">{{notifications.unchecked}} Não Lidas</strong> |
            <a href="{% url 'notifications:list_notifications_archive' %}"><strong class="text-warning">{{notifications.archived}} Arquivadas</strong> </a>
          </h6>
        </div>
          <div class="col-6 fs--2 text-end">
            {% if notifications.total_notification != 0%}
              {% if notifications.unchecked %}
                <a class="btn btn-falcon-primary btn-sm font-sans-serif ms-2 fs--2 mt-1"       
                class=" bg-light border-0 p-0 text-primary ms-2 fa-bounce" 
                href="{% url 'notifications:mark_all_read' %}"
                >Marcar todas como Lidas</a>
              {% endif %}
              {% if notifications.checkednotachive >= 1 %}
              <a class="btn btn-falcon-warning btn-sm font-sans-serif ms-2 fs--2 mt-1" 
              hx-post="{% url 'notifications:mark_all_archive' %}"  
              hx-target="#list_partial"              
              >Arquivar todas</a>
              {% endif %}

              {% if notifications.archived >= 1 %}              
              <a class="btn btn-falcon-info btn-sm font-sans-serif ms-2 fs--2 mt-1" 
              hx-post="{% url 'notifications:mark_all_unarchive' %}"
              hx-target="#list_partial"              
              >Desarquivar todas</a>
              {% endif %}
              {% if notifications.checkednotachive >= 1 %}               
                <a class="btn btn-falcon-danger btn-sm font-sans-serif ms-2 fs--2 mt-1" data-bs-toggle="collapse" 
                data-bs-target="#delete" aria-expanded="false" aria-controls="collapseExample">Deletar todas</a>
                  <div class="collapse text-end  mt-2" id="delete">
                    <span class="fs--2 fw-bold text-danger">Esta ação não poderá ser desfeita Todas as Mensagens Lidas e Arquivadas serão Excluídas!</span> 
                      <a class="font-sans-serif ms-2 ms-sm-3 text-success" 
                      hx-post="{% url 'notifications:delete_all_notifications' %}"
                      hx-target="#list_partial"           
                      type="button"     
                      >Confirmar</a>														
                  </div>                   
                {% endif %}
              {% else %}
            {% endif %}          
          </div>        
      </div>
    </div>

    {% if request.user.is_staff %}
      <div class="card-body fs--1 p-0" id="list-notifications"hx-get="{% url 'notifications:partial_notifications' %}"hx-trigger="every 30s" hx-swap="outerHTML">    
        {% include 'notifications/partials/_list_notifications.html' %}  
      </div>
    {% else %}
      <div class="card-body fs--1 p-0" id="list-notifications">    
          {% include 'notifications/partials/_list_notifications.html' %}  
      </div>
    {% endif %}
  </div>
</div>

          

notifications/templates/notifications/list_notifications_archive.html
<div id="list_partial">
<p>
  <h4 class="text-center">Arquivadas</h4>
</p>

  <div class="card overflow-hidden mb-3">
    <div class="card-header bg-light" >
      <div class="row flex-between-center">
        <div class="col-6 text-start mt-0">
          <a class="btn btn-falcon-primary btn-sm font-sans-serif fs--2" href="{% url 'notifications:list_notifications' %}">Ver Todas Notificações</a>

          <h6 class="mb-1 mb-md-0 mt-2">
            Notificações - {{notifications.total_notification}} | 
            <strong class="text-danger">{{notifications.unchecked}} Não Lidas</strong> |
            <a href="{% url 'notifications:list_notifications_archive' %}">
              <strong class="text-warning">{{notifications.archived}} Arquivadas</strong> </a>
          </h6>
        </div>
          <div class="col-6 fs--2 text-end">
            {% if notifications.total_notification != 0%}
              {% if notifications.archived >= 1 %}
                <a class="btn btn-falcon-info btn-sm font-sans-serif ms-2 fs--2 mt-1" 
                hx-post="{% url 'notifications:mark_all_unarchive' %}"
                hx-target="#list_partial">
                Desarquivar todas</a>
              
              <a class="btn btn-falcon-danger btn-sm font-sans-serif ms-2 fs--2 mt-1" 
                data-bs-toggle="collapse" data-bs-target="#delete" 
                aria-expanded="false" aria-controls="collapseExample">
                Deletar Arquivadas
              </a>
              <div class="collapse text-end  mt-2" id="delete">
                <span class="fs--2 fw-bold text-danger">
                  Esta ação não poderá ser desfeita. Todas notificações <strong>Arquivadas</strong> serão Excluídas!</span> 
                <a class="font-sans-serif ms-2 ms-sm-3 text-success" 
                hx-post="{% url 'notifications:delete_all_archive' %}"
                type="button"  
                hx-target="#list_partial">                 
                Confirmar</a>														
              </div> 
              {% endif %}
              {% else %}
            {% endif %}          
          </div>        
      </div>
    </div>
  
    {% include 'notifications/partials/_list_notifications_archive.html' %}

  </div>
</div>